-- Schema for the Healthcare Operations Analysis Database
CREATE SCHEMA `hospital_operation`;
CREATE TABLE `hospital_operation`.`hospital_details` (
    `Hospital_Name` text, 
    `City` text, 
    `Bed_Count` int
);
CREATE TABLE `hospital_operation`.`patient_admission_details` (
    `Patient_ID` text, 
    `Patient_Name` text, 
    `Age` int, 
    `Hospital_Name` text, 
    `Department` text, 
    `Doctor_Name` text, 
    `Diagnosis` text, 
    `Admission_Date` text, 
    `Discharge_Date` text, 
    `Bill_Amount` double, 
    `Status` text
);


--Queries for the Healthcare Operations Analysis Database

-- Task 1 - Resource Prioritization Resource Categorization (Logic & Arithmetic): Calculate the length of stay and CASE WHEN logic to segment patients based on their resource needs.
-- The Goal: Calculate the stay duration and categorize the patients.

SELECT Patient_Name, Department, 
DATEDIFF(Discharge_Date, Admission_Date) AS stay_duration,
CASE 
    WHEN DATEDIFF(Discharge_Date, Admission_Date) > 10 THEN 'Critical Care'
    WHEN DATEDIFF(Discharge_Date, Admission_Date) BETWEEN 5 AND 10 THEN 'Extended Care'
    ELSE 'Standard Care'
END AS Result_Prioritization
FROM patient_admission_details;

-- Task 2 - Financial Analysis Revenue Calculation (Logic & Arithmetic): Calculate the total revenue generated by each department and identify the top-performing departments.
-- The Goal: Calculate total revenue and identify top departments.

SELECT Department, SUM(Bill_Amount) AS Total_Revenue
FROM patient_admission_details
GROUP BY Department
ORDER BY Total_Revenue DESC;

--Task 3 - Identifying Department Bottlenecks
-- Patient Flow Analysis (Logic & Arithmetic): Analyze patient flow to identify bottlenecks in specific departments by calculating the average length of stay and patient count.
-- The Goal: Identify bottlenecks by analyzing patient flow. To know "Which department is struggling with the most 'Standard Care' cases?"

WITH Patient_Stats AS (
    SELECT Patient_Name, Department, 
           DATEDIFF(Discharge_Date, Admission_Date) AS stay_duration,
    CASE 
        WHEN DATEDIFF(Discharge_Date, Admission_Date) > 10 THEN 'Critical Care'
        WHEN DATEDIFF(Discharge_Date, Admission_Date) BETWEEN 5 AND 10 THEN 'Extended Care'
        ELSE 'Standard Care'
    END AS Result_Prioritization
    FROM patient_admission_details
)
SELECT Department, AVG(stay_duration) AS avg_days
FROM Patient_Stats
WHERE Result_Prioritization = 'Standard Care'
GROUP BY Department
ORDER BY avg_days DESC;

-- Task 4: Doctor Performance Analysis 
--The Problem: The hospital wants to see the total revenue (Bill_Amount) generated by each Doctor, but only for patients who are under 30 years old.
-- The Goal: Calculate the total revenue generated by each doctor for patients under 30 years old.
SELECT concat('$', Round(SUM(Bill_Amount), 2)) As Total_Revenue, Doctor_Name
From  patient_admission_details
WHERE Age < 30 
GROUP BY Doctor_Name;

-- Task 5 - City-wise Revenue Analysis
--The Goal: Find the Total Bill Amount for each City.

SELECT Concat('$',Round(SUM(h.Bill_Amount),2)) As Total_Amount,e.City
From healthcare_operations as h
Join hospital_details as e ON h.Hospital_Name = e.Hospital_Name
GROUP BY e.City;